name: Java 11 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{ "id": "github", "username": "user", "password": "${GH_PACKAGE_REPO_PASSWORD}" }]'
    
# Typical Java 11 workflow steps
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
           
      - name: Build with Maven
        run: mvn -B clean package
        env:
          GH_PACKAGE_REPO_PASSWORD: ${{ secrets.GH_PACKAGE_REPO_PASSWORD }}
        