name: Java 11 CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Typical Java 11 workflow steps
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
    
    # Step that does that actual cache save and restore
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
    
    # Step that runs the tests
      - name: Build with Maven
        run: mvn clean package